name: Build binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"

      - name: Build binaries
        run: |
          make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hypershift-binaries
          path: ./bin
